### ISSUE TITLE
عند كتابة الامر $ composer require ahmedghanem00/tempnumber-api-client

### ISSUE THREAD

**Issue by monazil** [ahmedghanem00/tempnumber-api-client#3]
https://repo.packagist.org could not be fully loaded (curl error 28 while downloading https://repo.packagist.org/packages.json: SSL connection timeout), package information was loaded from the local cache and may be out of date
./composer.json has been updated
Running composer update ahmedghanem00/tempnumber-api-client
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
5 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found.
Using version ^1.1 for ahmedghanem00/tempnumber-api-client

**Comment by ahmedghanem00** [comment]
Apparently, a network error. Try to clear the composer cache and re-install the package again.
